### ISSUE TITLE
파일 시간 받아오기 코드 작성

### ISSUE THREAD

**Issue by LimSH0731** [LimSH0731/Assignment2#6]
stat들에 받아온 값들 중 시간에 관한 값을 localtime을 이용해 tm 형 구조체에 저장합니다.

**Comment by LimSH0731** [comment]
문제 없이 작동합니다.

**Comment by LYHyoung** [comment]
해당 코드에 문제가 있는 것을 발견하였습니다.
Time1과 Time2의 값이 같아지는 것을 발견하였습니다.
